<?php

namespace Modules\Finance\GeneralLedger\Enums;

enum OperationalIdentityEnum: string
{
    // Foundation Identities V1
    case INVENTORY = 'INVENTORY';
    case GRNI_ACCRUAL = 'GRNI_ACCRUAL';
    case GRNI_RECEIPT = 'GRNI_RECEIPT';
    case AP_CONTROL = 'AP_CONTROL';
    case ACCRUED_EXPENSE = 'ACCRUED_EXPENSE';
    case VENDOR_PREPAYMENT = 'VENDOR_PREPAYMENT';
    case CASH_AND_BANK = 'CASH_AND_BANK';
    case COST_OF_CONSUMPTION = 'COST_OF_CONSUMPTION';
    case OPERATIONAL_EXPENSE = 'OPERATIONAL_EXPENSE';
    case AP_INVOICE_VARIANCE = 'AP_INVOICE_VARIANCE';
    case INVENTORY_ADJUSTMENT_GAIN = 'INVENTORY_ADJUSTMENT_GAIN';
    case INVENTORY_ADJUSTMENT_LOSS = 'INVENTORY_ADJUSTMENT_LOSS';
    case INVENTORY_WRITEOFF_LOSS = 'INVENTORY_WRITEOFF_LOSS';
    case AP_CREDIT_NOTE_GAIN = 'AP_CREDIT_NOTE_GAIN';
    case AP_WRITEOFF_GAIN = 'AP_WRITEOFF_GAIN';
    case AP_DEBIT_NOTE_RECEIVABLE = 'AP_DEBIT_NOTE_RECEIVABLE';
    case GRNI_ACCRUAL_REVISED = 'GRNI_ACCRUAL_REVISED';
    case VENDOR_TAX = 'VENDOR_TAX';

    // Extended Identities
    case PURCHASE_COMMITMENT = 'PURCHASE_COMMITMENT';
    case BUDGET_RESERVE = 'BUDGET_RESERVE';
}
