<?php

$migrationsPath = '/Users/gedeedi/Herd/ivorq/Modules/Operations/ContractorPTW/database/migrations';
if (!is_dir($migrationsPath)) mkdir($migrationsPath, 0755, true);

$migrations = [
    '2026_06_12_000001_create_contractor_companies_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('contractor_companies', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->string('name');\n            \$table->string('registration_number')->nullable();\n            \$table->string('status')->default('pending');\n            \$table->timestamps();\n            \$table->softDeletes();\n        });\n    }\n};\n",
    '2026_06_12_000002_create_contractor_worker_globals_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('contractor_worker_globals', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->char('company_id', 26);\n            \$table->string('first_name');\n            \$table->string('last_name');\n            \$table->string('email')->nullable();\n            \$table->string('phone')->nullable();\n            \$table->string('status')->default('approved');\n            \$table->timestamps();\n            \$table->softDeletes();\n        });\n    }\n};\n",
    '2026_06_12_000003_create_contractor_worker_property_profiles_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('contractor_worker_property_profiles', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->char('worker_global_id', 26);\n            \$table->char('property_id', 26);\n            \$table->string('status')->default('approved');\n            \$table->timestamps();\n            \$table->softDeletes();\n        });\n    }\n};\n",
    '2026_06_12_000004_create_contractor_insurances_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('contractor_insurances', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->char('company_id', 26);\n            \$table->string('policy_number');\n            \$table->string('provider_name');\n            \$table->date('valid_from');\n            \$table->date('valid_to');\n            \$table->timestamps();\n            \$table->softDeletes();\n        });\n    }\n};\n",
    '2026_06_12_000005_create_contractor_certifications_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('contractor_certifications', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->char('worker_global_id', 26);\n            \$table->string('certification_name');\n            \$table->date('valid_to')->nullable();\n            \$table->timestamps();\n        });\n    }\n};\n",
    '2026_06_12_000006_create_contractor_inductions_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('contractor_inductions', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->char('worker_profile_id', 26);\n            \$table->char('property_id', 26);\n            \$table->timestamp('induction_date');\n            \$table->timestamp('expiry_date');\n            \$table->timestamps();\n        });\n    }\n};\n",
    '2026_06_12_000007_create_contractor_access_passes_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('contractor_access_passes', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->char('worker_profile_id', 26);\n            \$table->char('property_id', 26);\n            \$table->timestamp('check_in_time');\n            \$table->timestamp('check_out_time')->nullable();\n            \$table->string('qr_code')->nullable();\n            \$table->timestamps();\n        });\n    }\n};\n",
    '2026_06_12_000008_create_permit_to_works_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('permit_to_works', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->char('property_id', 26);\n            \$table->char('work_order_id', 26)->nullable();\n            \$table->char('company_id', 26)->nullable();\n            \$table->string('permit_type');\n            \$table->string('status')->default('draft');\n            \$table->boolean('is_emergency')->default(false);\n            \$table->timestamp('valid_from')->nullable();\n            \$table->timestamp('valid_to')->nullable();\n            \$table->timestamps();\n            \$table->softDeletes();\n        });\n    }\n};\n",
    '2026_06_12_000009_create_permit_risk_assessments_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('permit_risk_assessments', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->char('permit_id', 26);\n            \$table->text('hazards');\n            \$table->text('control_measures');\n            \$table->string('initial_risk');\n            \$table->string('residual_risk');\n            \$table->timestamps();\n        });\n    }\n};\n",
    '2026_06_12_000010_create_permit_isolations_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('permit_isolations', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->char('permit_id', 26);\n            \$table->char('asset_id', 26);\n            \$table->string('isolation_type');\n            \$table->boolean('is_isolated')->default(false);\n            \$table->timestamps();\n        });\n    }\n};\n",
    '2026_06_12_000011_create_permit_approvals_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('permit_approvals', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->char('permit_id', 26);\n            \$table->char('approver_id', 26);\n            \$table->string('role');\n            \$table->string('status');\n            \$table->timestamp('approved_at')->nullable();\n            \$table->string('signature_hash')->nullable();\n            \$table->timestamps();\n        });\n    }\n};\n",
    '2026_06_12_000012_create_permit_attachments_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('permit_attachments', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->char('permit_id', 26);\n            \$table->string('file_path');\n            \$table->string('document_type');\n            \$table->timestamps();\n        });\n    }\n};\n",
    '2026_06_12_000013_create_permit_audits_table.php' => "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('permit_audits', function (Blueprint \$table) {\n            \$table->char('id', 26)->primary();\n            \$table->char('permit_id', 26);\n            \$table->char('property_id', 26);\n            \$table->string('action');\n            \$table->json('snapshot');\n            \$table->string('hash');\n            \$table->timestamps();\n        });\n    }\n};\n",
];

foreach ($migrations as $file => $content) {
    file_put_contents("$migrationsPath/$file", $content);
}

echo "Migrations generated.\\n";
