<?php

declare(strict_types=1);
$c=json_decode(file_get_contents($argv[1]??''),true);$db=$c['db_name'];$dir=$c['barrier_dir'];$base=$c['base_path'];$host=$c['db_host'];$port=$c['db_port'];$user=$c['db_user'];$pass=$c['db_pass'];
if(!preg_match('/^ivorq_concurrency_glf_c_[a-z0-9_-]+$/',$db)||$db==='ivorq_testing')exit(1);
function adminPdo($h,$p,$u,$x){return new PDO("pgsql:host={$h};port={$p};dbname=postgres",$u,$x,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);}
function dbPdo($h,$p,$d,$u,$x){return new PDO("pgsql:host={$h};port={$p};dbname={$d}",$u,$x,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);}
function qid($v){return '"'.preg_replace('/[^a-z0-9_-]/','',$v).'"';}
function table($t){return \Illuminate\Support\Facades\DB::table($t);}
function waitFile($p,$n,$s=90){$e=time()+$s;while(time()<$e){if(file_exists("{$p}/{$n}"))return;usleep(20000);}throw new RuntimeException("timeout {$n}");}
function runWorkers($c,$scenario,$fixture){$d=$c['barrier_dir'];foreach(glob($d.'/*')?:[]as$f)if(is_file($f)&&preg_match('/(ready|start|result|cfg)-/',basename($f)))@unlink($f);foreach(['A','B']as$id)file_put_contents("{$d}/cfg-{$id}.json",json_encode(['worker_id'=>$id,'scenario'=>$scenario,'barrier_dir'=>$d,'result_file'=>"{$d}/result-{$id}.json",'db_name'=>$c['db_name'],'base_path'=>$c['base_path'],'fixture'=>$fixture]));$script=$c['base_path'].'/tests/Postgres/Operations/PMS/Support/GuestDepositRefundArConcurrencyWorker.php';$desc=[0=>['pipe','r'],1=>['pipe','w']];$a=proc_open(PHP_BINARY.' '.escapeshellarg($script).' '.escapeshellarg("{$d}/cfg-A.json"),$desc,$pa,$c['base_path']);$b=proc_open(PHP_BINARY.' '.escapeshellarg($script).' '.escapeshellarg("{$d}/cfg-B.json"),$desc,$pb,$c['base_path']);foreach([$pa,$pb]as$ps){@fclose($ps[0]);@fclose($ps[1]);}waitFile($d,'ready-A');waitFile($d,'ready-B');touch("{$d}/start-{$scenario}.signal");waitFile($d,'result-A-ready');waitFile($d,'result-B-ready');@proc_close($a);@proc_close($b);$ra=json_decode(file_get_contents("{$d}/result-A.json"),true);$rb=json_decode(file_get_contents("{$d}/result-B.json"),true);$out=[$ra['outcome'],$rb['outcome']];sort($out);return['worker_a'=>$ra,'worker_b'=>$rb,'pid_different'=>$ra['pid']!==$rb['pid'],'pg_different'=>$ra['pg_backend_pid']!==$rb['pg_backend_pid'],'outcomes'=>$out];}
function seedReservation($property,$prefix){$g=(string)\Illuminate\Support\Str::ulid();$r=(string)\Illuminate\Support\Str::ulid();table('guests')->insert(['id'=>$g,'property_id'=>$property,'guest_code'=>$prefix.'-GST','full_name'=>$prefix.' Guest','guest_type'=>'individual','created_at'=>now(),'updated_at'=>now()]);table('reservations')->insert(['id'=>$r,'property_id'=>$property,'reservation_number'=>$prefix.'-RES','primary_guest_id'=>$g,'adults'=>1,'children'=>0,'arrival_date'=>'2026-07-10','departure_date'=>'2026-07-12','nights'=>2,'reservation_source'=>'walk_in','status'=>'tentative','reserved_room_type'=>'standard','created_at'=>now(),'updated_at'=>now()]);return['guest_id'=>$g,'reservation_id'=>$r];}
function seedFolio($property,$r,$g,$prefix,$charge='0.00'){$id=(string)\Illuminate\Support\Str::ulid();$w=((int)table('folios')->where('property_id',$property)->where('reservation_id',$r)->max('window_number'))+1;table('folios')->insert(['id'=>$id,'property_id'=>$property,'folio_number'=>$prefix.'-FOL','reservation_id'=>$r,'guest_id'=>$g,'status'=>'open','currency'=>'USD','window_number'=>$w,'opening_idempotency_key'=>$prefix.'-open','total_charges'=>$charge,'total_payments'=>'0.00','total_deposits'=>'0.00','total_ar_transfers'=>'0.00','balance'=>$charge,'created_at'=>now(),'updated_at'=>now()]);if(bccomp($charge,'0.00',2)>0)table('folio_items')->insert(['id'=>(string)\Illuminate\Support\Str::ulid(),'property_id'=>$property,'folio_id'=>$id,'item_type'=>'room_charge','description'=>'Concurrency charge','quantity'=>'1.00','amount'=>$charge,'is_void'=>false,'posted_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return$id;}
function countSql($pdo,$sql,$params=[]){$s=$pdo->prepare($sql);$s->execute($params);return(int)$s->fetchColumn();}
function confirmIntent($actor,$company,$property,$intent){session()->put('sensitive_action_confirmation',[$intent=>['actor_id'=>$actor,'intent'=>$intent,'company_id'=>$company,'property_id'=>$property,'confirmed_at'=>now()->toISOString(),'expires_at'=>now()->addMinutes(15)->toISOString()]]);}
$result=['db_created'=>false,'migrations_ok'=>false,'db_dropped'=>false,'protected_database'=>'ivorq_testing','error'=>null,'drop_error'=>null];
try{$a=adminPdo($host,$port,$user,$pass);$a->exec('DROP DATABASE IF EXISTS '.qid($db));$a->exec('CREATE DATABASE '.qid($db));$a=null;$result['db_created']=true;chdir($base);require$base.'/vendor/autoload.php';$app=require$base.'/bootstrap/app.php';$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();config(['database.connections.pgsql.database'=>$db]);\Illuminate\Support\Facades\DB::purge('pgsql');\Illuminate\Support\Facades\DB::reconnect('pgsql');\Illuminate\Support\Facades\Artisan::call('migrate',['--force'=>true]);$result['migrations_ok']=true;
$company=(string)\Illuminate\Support\Str::ulid();$property=(string)\Illuminate\Support\Str::ulid();$actor=(string)\Illuminate\Support\Str::ulid();$session=(string)\Illuminate\Support\Str::ulid();table('companies')->insert(['id'=>$company,'name'=>'GLFC Co','slug'=>'glfc-'.\Illuminate\Support\Str::random(5),'is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);table('properties')->insert(['id'=>$property,'company_id'=>$company,'name'=>'GLFC Property','slug'=>'glfc-prop-'.\Illuminate\Support\Str::random(5),'code'=>'GC'.\Illuminate\Support\Str::random(2),'timezone'=>'UTC','currency'=>'USD','is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);table('users')->insert(['id'=>$actor,'name'=>'GLFC Actor','email'=>'glfc-'.\Illuminate\Support\Str::random(5).'@test.local','password'=>\Illuminate\Support\Facades\Hash::make('password'),'is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);table('property_user')->insert(['user_id'=>$actor,'property_id'=>$property,'is_default'=>true,'status'=>'active','joined_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);table('cashier_sessions')->insert(['id'=>$session,'property_id'=>$property,'cashier_user_id'=>$actor,'status'=>'OPEN','opened_at'=>now(),'opened_by'=>$actor,'created_at'=>now(),'updated_at'=>now()]);
$perms=[\Modules\Operations\PMS\Services\GuestDepositLifecycleService::RECORD_PERMISSION,\Modules\Operations\PMS\Services\GuestDepositLifecycleService::APPLY_PERMISSION,\Modules\Operations\PMS\Services\GuestDepositLifecycleService::REVERSE_PERMISSION,\Modules\Operations\PMS\Services\GuestRefundLifecycleService::RECORD_PERMISSION,\Modules\Operations\PMS\Services\GuestPaymentLifecycleService::RECORD_PERMISSION,\Modules\Operations\PMS\Services\GuestPaymentLifecycleService::ALLOCATE_PERMISSION,\Modules\Operations\PMS\Services\GuestArTransferRequestService::REQUEST_PERMISSION,\Modules\Finance\AccountsReceivable\Services\GuestArTransferDecisionService::ACCEPT_PERMISSION,\Modules\Finance\AccountsReceivable\Services\GuestArTransferDecisionService::REJECT_PERMISSION,\Modules\Finance\AccountsReceivable\Services\GuestArTransferDecisionService::REVERSE_PERMISSION];foreach($perms as$p)\Modules\Foundation\Authorization\Models\Permission::firstOrCreate(['name'=>$p,'guard_name'=>'web']);app(\Spatie\Permission\PermissionRegistrar::class)->forgetCachedPermissions();$userModel=\Modules\Foundation\User\Models\User::findOrFail($actor);$userModel->givePermissionTo($perms);\Illuminate\Support\Facades\Auth::login($userModel);app(\Shared\Services\CurrentPropertyService::class)->setPropertyId($property);session(['active_property_id'=>$property,'current_property_id'=>$property,'active_company_id'=>$company]);$dep=app(\Modules\Operations\PMS\Services\GuestDepositLifecycleService::class);$pay=app(\Modules\Operations\PMS\Services\GuestPaymentLifecycleService::class);$req=app(\Modules\Operations\PMS\Services\GuestArTransferRequestService::class);$dec=app(\Modules\Finance\AccountsReceivable\Services\GuestArTransferDecisionService::class);$pdo=dbPdo($host,$port,$db,$user,$pass);$baseFixture=['company_id'=>$company,'property_id'=>$property,'actor_id'=>$actor,'cashier_session_id'=>$session];$wc=$c+['db_name'=>$db,'barrier_dir'=>$dir,'base_path'=>$base];
$r=seedReservation($property,'REC');$run=runWorkers($wc,'deposit_recording_replay',$baseFixture+['reservation_id'=>$r['reservation_id']]);$result['deposit_recording_replay']=$run+['rows'=>countSql($pdo,'select count(*) from guest_deposit_transactions where reservation_id=:r',['r'=>$r['reservation_id']])];
$aR=seedReservation($property,'NUMA');$bR=seedReservation($property,'NUMB');$run=runWorkers($wc,'deposit_number_safety',$baseFixture+['reservation_a'=>$aR['reservation_id'],'reservation_b'=>$bR['reservation_id']]);$result['deposit_number_safety']=$run+['rows'=>countSql($pdo,'select count(*) from guest_deposit_transactions where reservation_id in (:a,:b)',['a'=>$aR['reservation_id'],'b'=>$bR['reservation_id']]),'numbers'=>countSql($pdo,'select count(distinct deposit_number) from guest_deposit_transactions where reservation_id in (:a,:b)',['a'=>$aR['reservation_id'],'b'=>$bR['reservation_id']])];
foreach([['deposit_application_replay','APR','50.00'],['deposit_over_application','OVER','60.00']]as[$scenario,$prefix,$amt]){$x=seedReservation($property,$prefix);$folio=seedFolio($property,$x['reservation_id'],$x['guest_id'],$prefix);$deposit=$dep->recordCashDeposit($userModel,$x['reservation_id'],$session,'100.00','setup-'.$scenario);$run=runWorkers($wc,$scenario,$baseFixture+['deposit_id'=>$deposit->id,'folio_id'=>$folio]);$result[$scenario]=$run+['applications'=>countSql($pdo,'select count(*) from guest_deposit_applications where guest_deposit_transaction_id=:d',['d'=>$deposit->id]),'items'=>countSql($pdo,"select count(*) from folio_items where item_type='deposit' and folio_id=:f",['f'=>$folio]),'resolved'=>countSql($pdo,'select coalesce(sum(amount),0) from guest_deposit_applications where guest_deposit_transaction_id=:d',['d'=>$deposit->id])];}
$x=seedReservation($property,'SPLIT');$fa=seedFolio($property,$x['reservation_id'],$x['guest_id'],'SPLA');$fb=seedFolio($property,$x['reservation_id'],$x['guest_id'],'SPLB');$deposit=$dep->recordCashDeposit($userModel,$x['reservation_id'],$session,'100.00','setup-split');$run=runWorkers($wc,'deposit_split',$baseFixture+['deposit_id'=>$deposit->id,'folio_a'=>$fa,'folio_b'=>$fb]);$result['deposit_split']=$run+['applications'=>countSql($pdo,'select count(*) from guest_deposit_applications where guest_deposit_transaction_id=:d',['d'=>$deposit->id]),'status'=>$pdo->query("select lifecycle_status from guest_deposit_transactions where id='{$deposit->id}'")->fetchColumn()];
$x=seedReservation($property,'REV');$folio=seedFolio($property,$x['reservation_id'],$x['guest_id'],'REV');$deposit=$dep->recordCashDeposit($userModel,$x['reservation_id'],$session,'50.00','setup-rev');$appRow=$dep->applyDeposit($userModel,$deposit->id,$folio,'50.00','setup-rev-app');$run=runWorkers($wc,'deposit_double_reversal',$baseFixture+['application_id'=>$appRow->id]);$result['deposit_double_reversal']=$run+['reversals'=>countSql($pdo,"select count(*) from guest_deposit_reversals where guest_deposit_application_id=:a",['a'=>$appRow->id]),'items'=>countSql($pdo,"select count(*) from folio_items where item_type='deposit_reversal' and folio_id=:f",['f'=>$folio])];
$x=seedReservation($property,'DVR');$folio=seedFolio($property,$x['reservation_id'],$x['guest_id'],'DVR');$deposit=$dep->recordCashDeposit($userModel,$x['reservation_id'],$session,'100.00','setup-dvr');$run=runWorkers($wc,'deposit_application_vs_refund',$baseFixture+['deposit_id'=>$deposit->id,'folio_id'=>$folio]);$result['deposit_application_vs_refund']=$run+['resolved'=>countSql($pdo,"select coalesce((select sum(amount) from guest_deposit_applications where guest_deposit_transaction_id=:d),0)+coalesce((select sum(amount) from guest_refund_transactions where guest_deposit_transaction_id=:d),0)",['d'=>$deposit->id])];
$x=seedReservation($property,'PVR');$folio=seedFolio($property,$x['reservation_id'],$x['guest_id'],'PVR');$payment=$pay->recordCashPayment($userModel,$x['reservation_id'],$session,'100.00','setup-pvr');$run=runWorkers($wc,'payment_allocation_vs_refund',$baseFixture+['payment_id'=>$payment->id,'folio_id'=>$folio]);$result['payment_allocation_vs_refund']=$run+['resolved'=>countSql($pdo,"select coalesce((select sum(amount) from guest_payment_allocations where guest_payment_transaction_id=:p),0)+coalesce((select sum(amount) from guest_refund_transactions where guest_payment_transaction_id=:p),0)",['p'=>$payment->id])];
foreach([['ar_accept_reject','ARD'],['ar_double_accept','ARA']]as[$scenario,$prefix]){$x=seedReservation($property,$prefix);$folio=seedFolio($property,$x['reservation_id'],$x['guest_id'],$prefix,'100.00');$request=$req->requestTransfer($userModel,$folio,'80.00','DIRECT','setup-'.$scenario);$run=runWorkers($wc,$scenario,$baseFixture+['request_id'=>$request->id]);$result[$scenario]=$run+['terminal'=>countSql($pdo,"select count(*) from guest_ar_transfer_decisions where guest_ar_transfer_request_id=:r and decision_type in ('ACCEPTED','REJECTED')",['r'=>$request->id]),'items'=>countSql($pdo,"select count(*) from folio_items where item_type='ar_transfer' and folio_id=:f",['f'=>$folio])];}
$x=seedReservation($property,'ARF');$folio=seedFolio($property,$x['reservation_id'],$x['guest_id'],'ARF','100.00');$request=$req->requestTransfer($userModel,$folio,'80.00','DIRECT','setup-arf');$deposit=$dep->recordCashDeposit($userModel,$x['reservation_id'],$session,'40.00','setup-arf-deposit');$run=runWorkers($wc,'ar_accept_vs_deposit',$baseFixture+['request_id'=>$request->id,'deposit_id'=>$deposit->id,'folio_id'=>$folio]);$fs=$pdo->query("select total_deposits,total_ar_transfers,balance from folios where id='{$folio}'")->fetch(PDO::FETCH_ASSOC);$result['ar_accept_vs_deposit']=$run+['totals'=>$fs,'negative'=>bccomp($fs['balance'],'0.00',2)<0];
$x=seedReservation($property,'ARR');$folio=seedFolio($property,$x['reservation_id'],$x['guest_id'],'ARR','100.00');$request=$req->requestTransfer($userModel,$folio,'100.00','DIRECT','setup-arr');confirmIntent($actor,$company,$property,\Modules\Finance\AccountsReceivable\Services\GuestArTransferDecisionService::ACCEPT_INTENT);$dec->acceptTransfer($userModel,$request->id,'ACCEPT','setup-arr-accept');$run=runWorkers($wc,'ar_double_reversal',$baseFixture+['request_id'=>$request->id]);$result['ar_double_reversal']=$run+['reversals'=>countSql($pdo,"select count(*) from guest_ar_transfer_decisions where guest_ar_transfer_request_id=:r and decision_type='REVERSED'",['r'=>$request->id]),'items'=>countSql($pdo,"select count(*) from folio_items where item_type='ar_transfer_reversal' and folio_id=:f",['f'=>$folio])];$pdo=null;
}catch(Throwable$e){$result['error']=$e->getMessage().' at '.$e->getFile().':'.$e->getLine();}
try{\Illuminate\Support\Facades\DB::disconnect();\Illuminate\Support\Facades\DB::purge('pgsql');}catch(Throwable){}try{$a=adminPdo($host,$port,$user,$pass);$s=$a->prepare('select pg_terminate_backend(pid) from pg_stat_activity where datname=:d and pid<>pg_backend_pid()');$s->execute(['d'=>$db]);$a->exec('DROP DATABASE IF EXISTS '.qid($db));$result['db_dropped']=true;}catch(Throwable$e){$result['drop_error']=$e->getMessage();}file_put_contents($c['result_file'],json_encode($result,JSON_PRETTY_PRINT));
