<?php

declare(strict_types=1);

$cfg=json_decode(file_get_contents($argv[1]??''),true);$id=$cfg['worker_id'];$scenario=$cfg['scenario'];$dir=$cfg['barrier_dir'];$f=$cfg['fixture'];
require $cfg['base_path'].'/vendor/autoload.php';$app=require $cfg['base_path'].'/bootstrap/app.php';$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();
config(['database.connections.pgsql.database'=>$cfg['db_name']]);\Illuminate\Support\Facades\DB::purge('pgsql');\Illuminate\Support\Facades\DB::reconnect('pgsql');
$actor=\Modules\Foundation\User\Models\User::findOrFail($f['actor_id']);\Illuminate\Support\Facades\Auth::login($actor);app(\Shared\Services\CurrentPropertyService::class)->setPropertyId($f['property_id']);session(['active_property_id'=>$f['property_id'],'current_property_id'=>$f['property_id'],'active_company_id'=>$f['company_id']]);
$result=['worker_id'=>$id,'pid'=>getmypid(),'pg_backend_pid'=>-1,'outcome'=>'UNKNOWN','hidden_error'=>null,'id'=>null,'number'=>null];touch("{$dir}/ready-{$id}");$start="{$dir}/start-{$scenario}.signal";$end=time()+90;while(time()<$end&&!file_exists($start))usleep(20000);
function glfcConfirm(array $f,string $intent):void{session()->put('sensitive_action_confirmation',[$intent=>['actor_id'=>$f['actor_id'],'intent'=>$intent,'company_id'=>$f['company_id'],'property_id'=>$f['property_id'],'confirmed_at'=>now()->toISOString(),'expires_at'=>now()->addMinutes(15)->toISOString()]]);}
try{
 $result['pg_backend_pid']=(int)\Illuminate\Support\Facades\DB::selectOne('select pg_backend_pid() pid')->pid;
 $deposits=app(\Modules\Operations\PMS\Services\GuestDepositLifecycleService::class);$refunds=app(\Modules\Operations\PMS\Services\GuestRefundLifecycleService::class);$payments=app(\Modules\Operations\PMS\Services\GuestPaymentLifecycleService::class);$requests=app(\Modules\Operations\PMS\Services\GuestArTransferRequestService::class);$decisions=app(\Modules\Finance\AccountsReceivable\Services\GuestArTransferDecisionService::class);
 if($scenario==='deposit_recording_replay'||$scenario==='deposit_number_safety'){$rid=$scenario==='deposit_number_safety'?($id==='A'?$f['reservation_a']:$f['reservation_b']):$f['reservation_id'];$key=$scenario==='deposit_number_safety'?'deposit-number-'.$id:'deposit-replay';$row=$deposits->recordCashDeposit($actor,$rid,$f['cashier_session_id'],'100.00',$key);$result['id']=$row->id;$result['number']=$row->deposit_number;$result['outcome']='DEPOSIT_RECORDED';}
 elseif(in_array($scenario,['deposit_application_replay','deposit_over_application','deposit_split'],true)){$folio=$scenario==='deposit_split'?($id==='A'?$f['folio_a']:$f['folio_b']):$f['folio_id'];$amount=$scenario==='deposit_split'?($id==='A'?'60.00':'40.00'):($scenario==='deposit_application_replay'?'50.00':'60.00');$key=$scenario==='deposit_application_replay'?'application-replay':$scenario.'-'.$id;try{$row=$deposits->applyDeposit($actor,$f['deposit_id'],$folio,$amount,$key);$result['id']=$row->id;$result['outcome']='DEPOSIT_APPLIED';}catch(\DomainException $e){if(str_contains($e->getMessage(),'OVER_APPLICATION'))$result['outcome']='BOUNDED_REJECT';else throw $e;}}
 elseif($scenario==='deposit_double_reversal'){glfcConfirm($f,\Modules\Operations\PMS\Services\GuestDepositLifecycleService::REVERSE_INTENT);$row=$deposits->reverseDepositApplication($actor,$f['application_id'],'RACE','deposit-reversal-replay');$result['id']=$row->id;$result['outcome']='DEPOSIT_REVERSED';}
 elseif($scenario==='deposit_application_vs_refund'){if($id==='A'){$row=$deposits->applyDeposit($actor,$f['deposit_id'],$f['folio_id'],'70.00','app-vs-refund');$result['id']=$row->id;$result['outcome']='DEPOSIT_APPLIED';}else{glfcConfirm($f,\Modules\Operations\PMS\Services\GuestRefundLifecycleService::CONFIRMATION_INTENT);try{$row=$refunds->recordCashRefund($actor,'GUEST_DEPOSIT',$f['deposit_id'],$f['cashier_session_id'],'50.00','RACE','refund-vs-app');$result['id']=$row->id;$result['outcome']='REFUND_RECORDED';}catch(\DomainException $e){if(str_contains($e->getMessage(),'EXCEEDS_AVAILABLE'))$result['outcome']='BOUNDED_REJECT';else throw $e;}}}
 elseif($scenario==='payment_allocation_vs_refund'){if($id==='A'){try{$row=$payments->allocatePayment($actor,$f['payment_id'],$f['folio_id'],'70.00','pay-alloc-race');$result['id']=$row->id;$result['outcome']='PAYMENT_ALLOCATED';}catch(\DomainException $e){if(str_contains($e->getMessage(),'OVER_ALLOCATION'))$result['outcome']='BOUNDED_REJECT';else throw $e;}}else{glfcConfirm($f,\Modules\Operations\PMS\Services\GuestRefundLifecycleService::CONFIRMATION_INTENT);try{$row=$refunds->recordCashRefund($actor,'GUEST_PAYMENT',$f['payment_id'],$f['cashier_session_id'],'50.00','RACE','pay-refund-race');$result['id']=$row->id;$result['outcome']='REFUND_RECORDED';}catch(\DomainException $e){if(str_contains($e->getMessage(),'EXCEEDS_AVAILABLE'))$result['outcome']='BOUNDED_REJECT';else throw $e;}}}
 elseif($scenario==='ar_accept_reject'){if($id==='A'){glfcConfirm($f,\Modules\Finance\AccountsReceivable\Services\GuestArTransferDecisionService::ACCEPT_INTENT);try{$row=$decisions->acceptTransfer($actor,$f['request_id'],'ACCEPT','ar-accept');$result['id']=$row->id;$result['outcome']='AR_ACCEPTED';}catch(\DomainException){$result['outcome']='TERMINAL_REJECT';}}else{glfcConfirm($f,\Modules\Finance\AccountsReceivable\Services\GuestArTransferDecisionService::REJECT_INTENT);try{$row=$decisions->rejectTransfer($actor,$f['request_id'],'REJECT','ar-reject');$result['id']=$row->id;$result['outcome']='AR_REJECTED';}catch(\DomainException){$result['outcome']='TERMINAL_REJECT';}}}
 elseif($scenario==='ar_double_accept'){glfcConfirm($f,\Modules\Finance\AccountsReceivable\Services\GuestArTransferDecisionService::ACCEPT_INTENT);$row=$decisions->acceptTransfer($actor,$f['request_id'],'ACCEPT','ar-double-accept');$result['id']=$row->id;$result['outcome']='AR_ACCEPTED';}
 elseif($scenario==='ar_accept_vs_deposit'){if($id==='A'){glfcConfirm($f,\Modules\Finance\AccountsReceivable\Services\GuestArTransferDecisionService::ACCEPT_INTENT);try{$row=$decisions->acceptTransfer($actor,$f['request_id'],'ACCEPT','ar-folio-race');$result['id']=$row->id;$result['outcome']='AR_ACCEPTED';}catch(\DomainException){$result['outcome']='BOUNDED_REJECT';}}else{$row=$deposits->applyDeposit($actor,$f['deposit_id'],$f['folio_id'],'40.00','deposit-folio-race');$result['id']=$row->id;$result['outcome']='DEPOSIT_APPLIED';}}
 elseif($scenario==='ar_double_reversal'){glfcConfirm($f,\Modules\Finance\AccountsReceivable\Services\GuestArTransferDecisionService::REVERSE_INTENT);try{$row=$decisions->reverseAcceptedTransfer($actor,$f['request_id'],'REVERSE','ar-double-reverse');$result['id']=$row->id;$result['outcome']='AR_REVERSED';}catch(\DomainException $e){if(str_contains($e->getMessage(),'accepted AR transfer'))$result['outcome']='ALREADY_REVERSED';else throw $e;}}
}catch(Throwable $e){$result['outcome']='CONTROLLED_FAILURE';$result['hidden_error']=$e::class.': '.$e->getMessage();}
file_put_contents($cfg['result_file'],json_encode($result,JSON_PRETTY_PRINT));touch("{$dir}/result-{$id}-ready");
