<?php

namespace Modules\Operations\PMS\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Modules\Operations\Housekeeping\Enums\RoomTypeEnum;
use Modules\Operations\PMS\Enums\ReservationSourceEnum;
use Modules\Operations\PMS\Models\Reservation;
use Shared\Services\CurrentPropertyService;

class StoreReservationRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()->can('create', Reservation::class);
    }

    public function rules(): array
    {
        $propertyId = app(CurrentPropertyService::class)->getId();

        return [
            'primary_guest_id'   => ['required', 'string', 'size:26',
                Rule::exists('guests', 'id')->where('property_id', $propertyId)->whereNull('deleted_at'),
            ],
            'rate_plan_id'       => ['nullable', 'string', 'size:26',
                Rule::exists('rate_plans', 'id')->where('property_id', $propertyId)->whereNull('deleted_at'),
            ],
            'arrival_date'       => ['required', 'date'],
            'departure_date'     => ['required', 'date', 'after:arrival_date'],
            'nights'             => ['nullable', 'integer', 'min:1'],
            'adults'             => ['nullable', 'integer', 'min:1', 'max:20'],
            'children'           => ['nullable', 'integer', 'min:0', 'max:20'],
            'reservation_source' => ['nullable', Rule::enum(ReservationSourceEnum::class)],
            'reserved_room_type' => ['required', Rule::enum(RoomTypeEnum::class)],
            'assigned_room_id'   => ['nullable', 'string', 'size:26',
                Rule::exists('rooms', 'id')->where('property_id', $propertyId)->whereNull('deleted_at'),
            ],
            'remarks'            => ['nullable', 'string'],

            // Auto-generated by the service — must not be provided
            'reservation_number' => ['prohibited'],
            // Lifecycle fields are server-controlled
            'status'             => ['prohibited'],
            // Check-in/out timestamps live on Stay, not Reservation
            'check_in_at'        => ['prohibited'],
            'check_out_at'       => ['prohibited'],
            // Financial totals belong to Folio, not Reservation
            'total_charges'      => ['prohibited'],
            'total_payments'     => ['prohibited'],
            'balance'            => ['prohibited'],
        ];
    }
}
