<?php

namespace Modules\Operations\PMS\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Modules\Operations\PMS\Enums\GuestTypeEnum;
use Modules\Operations\PMS\Models\Guest;

class StoreGuestRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()->can('create', Guest::class);
    }

    public function rules(): array
    {
        return [
            'full_name'   => ['required', 'string', 'max:255'],
            'email'       => ['nullable', 'email', 'max:255'],
            'phone'       => ['nullable', 'string', 'max:50'],
            'nationality' => ['nullable', 'string', 'max:100'],
            'id_type'     => ['nullable', 'string', 'max:50'],
            'id_number'   => ['nullable', 'string', 'max:100'],
            'guest_type'  => ['nullable', Rule::enum(GuestTypeEnum::class)],
            'vip_level'   => ['nullable', 'integer', 'min:1', 'max:5'],
            'notes'       => ['nullable', 'string'],

            // guest_code is auto-generated by the service — must not be provided
            'guest_code'  => ['prohibited'],
            // Audit columns are server-managed via HasAuditColumns
            'created_by'  => ['prohibited'],
            'updated_by'  => ['prohibited'],
        ];
    }
}
