<?php

namespace Modules\Finance\Banking\Enums;

enum BankingMigrationExceptionCodeEnum: string
{
    case SOURCE_PROPERTY_SCOPE_UNAVAILABLE = 'SOURCE_PROPERTY_SCOPE_UNAVAILABLE';
    case SOURCE_IDENTITY_UNAVAILABLE = 'SOURCE_IDENTITY_UNAVAILABLE';
    case SOURCE_SNAPSHOT_UNAVAILABLE = 'SOURCE_SNAPSHOT_UNAVAILABLE';
    case DUPLICATE_SOURCE_IDENTITY = 'DUPLICATE_SOURCE_IDENTITY';
    case UNSUPPORTED_LEGACY_SOURCE_TYPE = 'UNSUPPORTED_LEGACY_SOURCE_TYPE';
    case CROSS_PROPERTY_SOURCE_INCONSISTENCY = 'CROSS_PROPERTY_SOURCE_INCONSISTENCY';
    case TARGET_MAPPING_REQUIRED = 'TARGET_MAPPING_REQUIRED';
    case FINANCIAL_VALUE_REQUIRED = 'FINANCIAL_VALUE_REQUIRED';
    case EXECUTION_NOT_AUTHORIZED = 'EXECUTION_NOT_AUTHORIZED';
    case EXECUTION_SOURCE_ALREADY_CLAIMED = 'EXECUTION_SOURCE_ALREADY_CLAIMED';
    case EXECUTION_TARGET_ALREADY_CLAIMED = 'EXECUTION_TARGET_ALREADY_CLAIMED';
    case EXECUTION_SOURCE_SNAPSHOT_CHANGED = 'EXECUTION_SOURCE_SNAPSHOT_CHANGED';
}
