<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('guests', function (Blueprint $table) {
            $table->char('id', 26)->primary();
            $table->char('property_id', 26);

            // Unique guest code per property (auto-generated by observer/service)
            $table->string('guest_code', 20);

            $table->string('full_name', 255);
            $table->string('email', 255)->nullable();
            $table->string('phone', 50)->nullable();
            $table->string('nationality', 100)->nullable();

            // Identity document
            $table->string('id_type', 50)->nullable();   // passport, nric, driving_licence, etc.
            $table->string('id_number', 100)->nullable();

            $table->string('guest_type', 30)->default('individual');
            $table->tinyInteger('vip_level')->unsigned()->nullable(); // 1-5 scale, null = not VIP
            $table->text('notes')->nullable();

            $table->char('created_by', 26)->nullable();
            $table->char('updated_by', 26)->nullable();
            $table->timestamps();
            $table->softDeletes();

            $table->foreign('property_id')->references('id')->on('properties')->restrictOnDelete();

            $table->unique(['property_id', 'guest_code']);
            $table->index(['property_id', 'guest_type']);
            $table->index(['property_id', 'email']);
            $table->index(['property_id', 'full_name']);
            $table->index(['property_id', 'vip_level']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('guests');
    }
};
